### ISSUE TITLE
No module named 'spatialconverter'

### ISSUE THREAD

**Issue by alex-seville** [studiolanes/vision-utils#3]
This is awesome, thanks for sharing this code.

When I tried to run it I received the following error:

`main.py", line 4, in <module>
    from spatialconverter.image_handler import ImageHandler
ModuleNotFoundError: No module named 'spatialconverter'`

Any ideas?

Thanks.

**Comment by fangherk** [comment]
Thanks for trying it out! Seems like you might not be in the right virtual environment. Did you run the command after calling `poetry shell`?

**Comment by alex-seville** [comment]
I think so

`Spawning shell within /Users/<..>/Library/Caches/pypoetry/virtualenvs/spatialconverter-d5vfbJye-py3.12
 spatialconverter % emulate bash -c '. /Users/<..>/Library/Caches/pypoetry/virtualenvs/spatialconverter-d5vfbJye-py3.12/bin/activate'
(spatialconverter-py3.12)` is what I saw in the terminal

**Comment by alex-seville** [comment]
Any environment variables required?

**Comment by fangherk** [comment]
No environment variables needed. It seems like you're not in the right python virtual environment.

When you run `which python`, what do you get? 

This is what I think you're probably seeing:
```bash
╰─$ which python # when using the wrong virtual environment
/Users/herk/.pyenv/shims/python
╰─$ python                                                         
Python 3.10.13 (main, Sep  9 2023, 21:50:46) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from spatialconverter.image_handler import ImageHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'spatialconverter'
```

If you're in the poetry shell, you'll see
```bash
╭─herk@Herricks-MacBook-Pro ~/Projects/visionViewer/spatialconverter ‹main›
╰─$ poetry shell
Spawning shell within /Users/herk/Projects/visionViewer/spatialconverter/.venv
╭─herk@Herricks-MacBook-Pro ~/Projects/visionViewer/spatialconverter ‹main›
╰─$ emulate bash -c '. /Users/herk/Projects/visionViewer/spatialconverter/.venv/bin
/activate'
(spatialconverter-py3.10) ╭─herk@Herricks-MacBook-Pro ~/Projects/visionViewer/spatialconverter ‹main›
╰─$ which python
/Users/herk/Projects/visionViewer/spatialconverter/.venv/bin/python
(spatialconverter-py3.10) ╭─herk@Herricks-MacBook-Pro ~/Projects/visionViewer/spatialconverter ‹main›
╰─$ python
Python 3.10.13 (main, Sep  9 2023, 21:50:46) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from spatialconverter.image_handler import ImageHandler
```

**Comment by alex-seville** [comment]
yep, there's something going on with my python/python3

```

(spatialconverter-py3.12) seville spatialconverter % which python
python: aliased to /usr/bin/python3
(spatialconverter-py3.12) seville spatialconverter % which python3
/Users/seville/Library/Caches/pypoetry/virtualenvs/spatialconverter-d5vfbJye-py3.12/bin/python3

```

**Comment by alex-seville** [comment]
and of course using `python3` n the run command made it work. Thanks for the support, got it working now!
